name: Sync to Public and Deploy Coverage

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-to-public:
    runs-on: [self-hosted, Windows, X64, test]
    steps:
      - name: Checkout private repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Setup Git
        run: |
          $env:PATH = "C:\Program Files\Git\bin;C:\Program Files\Git\cmd;" + $env:PATH
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      
      - name: Remove sensitive files and push to public
        run: |
          # Use full path to Git
          $git = "C:\Program Files\Git\cmd\git.exe"
          
          # Get current directory
          $currentDir = Get-Location
          
          # Create temporary directory
          $tempDir = Join-Path $env:TEMP ("git-sync-" + (Get-Date -Format "yyyyMMddHHmmss"))
          New-Item -ItemType Directory -Path $tempDir -Force
          
          # Clone repository
          & $git clone $currentDir $tempDir
          
          # Change to temp directory
          Set-Location $tempDir
          
          # Get list of files marked for encryption in .gitattributes
          $encryptedFiles = @()
          if (Test-Path .gitattributes) {
            Get-Content .gitattributes | ForEach-Object {
              if ($_ -match '^(.+?)\s+filter=git-crypt') {
                $encryptedFiles += $matches[1]
              }
            }
          }
          
          # Remove encrypted files and .gitattributes from working directory
          foreach ($file in $encryptedFiles) {
            if (Test-Path $file) {
              Remove-Item $file -Force
            }
          }
          Remove-Item .gitattributes -Force -ErrorAction SilentlyContinue
          
          # Commit the removal
          & $git add -A
          & $git commit -m "Remove sensitive files for public repository" 2>$null
          
          # Add public remote and push
          & $git remote add public https://x-access-token:${{ secrets.PUBLIC_REPO_TOKEN }}@github.com/ohishi-yhonda-pub/drive-api.git
          & $git push public HEAD:main --force
          
          # Cleanup
          Set-Location $currentDir
          Remove-Item -Recurse -Force $tempDir

  deploy-coverage:
    needs: sync-to-public
    runs-on: [self-hosted, Windows, X64, test]
    steps:
      - name: Checkout public repository
        uses: actions/checkout@v4
        with:
          repository: ohishi-yhonda-pub/drive-api
          token: ${{ secrets.PUBLIC_REPO_TOKEN }}
      
      - name: Setup Git
        run: |
          $env:PATH = "C:\Program Files\Git\bin;C:\Program Files\Git\cmd;" + $env:PATH
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      - name : set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Run tests and generate coverage
        run: npm run test:coverage
      

      - name: Deploy coverage to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.PUBLIC_REPO_TOKEN }}
          publish_dir: coverage
          publish_branch: gh-pages
          force_orphan: true
          external_repository: ohishi-yhonda-pub/drive-api
        env:
          PATH: "C:\\Program Files\\Git\\bin;C:\\Program Files\\Git\\cmd;${{ env.PATH }}"