name: Generate Docs and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-and-deploy:
    runs-on: [self-hosted, Windows, X64, test]
    steps:
      - name: Process and Deploy
        shell: bash
        run: |
          # Create temp directory
          tempDir="/tmp/deploy-$(date +%Y%m%d%H%M%S)"
          mkdir -p "$tempDir"
          cd "$tempDir"
          
          # Clone private repository
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ohishi-yhonda-org/drive-api.git private
          cd private
          
          # Install dependencies
          npm ci
          
          # Copy template for Wrangler
          if [ -f .dev.vars.template ]; then
            cp .dev.vars.template .dev.vars
          fi
          
          # Start Wrangler and generate OpenAPI
          npx wrangler dev --port 8787 --local &
          wranglerPID=$!
          sleep 5
          
          # Wait for server and fetch OpenAPI
          maxAttempts=30
          for i in $(seq 1 $maxAttempts); do
            if curl -s http://localhost:8787/specification > docs/openapi.json; then
              echo "OpenAPI specification generated"
              break
            fi
            if [ $i -eq $maxAttempts ]; then
              echo "Wrangler failed to start"
              exit 1
            fi
            sleep 2
          done
          
          # Stop Wrangler
          kill $wranglerPID || true
          rm -f .dev.vars
          
          # Run tests and generate coverage
          npm run test:coverage
          
          # Remove sensitive files
          if [ -f .gitattributes ]; then
            while IFS= read -r line; do
              if [[ $line =~ ^([^[:space:]]+)[[:space:]]+filter=git-crypt ]]; then
                file="${BASH_REMATCH[1]}"
                [ -f "$file" ] && rm -f "$file"
              fi
            done < .gitattributes
            rm -f .gitattributes
          fi
          
          # Push to public repository
          git add -A
          git commit -m "Update for public repository" --allow-empty
          git remote add public https://x-access-token:${{ secrets.PUBLIC_REPO_TOKEN }}@github.com/ohishi-yhonda-pub/drive-api.git
          git push public HEAD:main --force
          
          # Deploy to GitHub Pages
          cd ..
          git clone https://x-access-token:${{ secrets.PUBLIC_REPO_TOKEN }}@github.com/ohishi-yhonda-pub/drive-api.git public
          cd public
          
          # Checkout gh-pages branch
          git checkout gh-pages 2>/dev/null || git checkout --orphan gh-pages
          
          # Clear existing content
          find . -maxdepth 1 -name .git -prune -o -exec rm -rf {} + 2>/dev/null || true
          
          # Copy new content
          cp -r ../private/coverage .
          cp -r ../private/docs/* .
          
          # Commit and push
          git add -A
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages --force
          
          # Cleanup
          cd /tmp
          rm -rf "$tempDir"