name: Generate Docs and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-and-deploy:
    runs-on: [self-hosted, Windows, X64, test]
    steps:
      - name: Checkout repository  
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Deploy Drive API
        uses: ./.github/actions/drive-api-deploy
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          public-repo-token: ${{ secrets.PUBLIC_REPO_TOKEN }}
          private-repo: ohishi-yhonda-org/drive-api
          public-repo: ohishi-yhonda-pub/drive-api